custom_rules:
  spatial_reference_web_mercator:
    name: Web Mercator Spatial Reference
    regex: AGSSpatialReference\(wkid:\s*(3857|102100)\)
    message: "Use AGSSpatialReference.webMercator() instead."

disabled_rules: # rule identifiers to exclude from running
  - block_based_kvo
  - cyclomatic_complexity
  - file_length
  - for_where
  - force_cast
  - function_body_length
  - identifier_name
  - line_length
  - statement_position
  - trailing_whitespace
  - type_name
  - unused_closure_parameter
