disabled_rules: # rule identifiers to exclude from running
  - block_based_kvo
  - colon
  - comma
  - control_statement
  - cyclomatic_complexity
  - file_length
  - for_where
  - force_cast
  - force_try
  - function_body_length
  - identifier_name
  - line_length
  - mark
  - multiple_closures_with_trailing_closure
  - opening_brace
  - redundant_discardable_let
  - return_arrow_whitespace
  - statement_position
  - syntactic_sugar
  - trailing_semicolon
  - trailing_whitespace
  - type_name
  - unused_closure_parameter
  - unused_optional_binding
  - vertical_whitespace
